#ifndef NXPP_MODULAR_COMPONENTS_HPP
#define NXPP_MODULAR_COMPONENTS_HPP

// Generated from include/nxpp.hpp by scripts/sync_modular_headers.py.
// Do not edit this file directly: keep include/nxpp.hpp as the single source of truth.

#include "types.hpp"

namespace nxpp {

template <typename GraphWrapper>
auto connected_component_groups(const GraphWrapper& G) {
    using NodeID = typename GraphWrapper::NodeType;
    auto& g = G.get_impl();
    auto& bgl_to_id = G.get_bgl_to_id_map();

    int n = boost::num_vertices(g);
    std::vector<int> comp(n);
    int num = boost::connected_components(g, boost::make_iterator_property_map(comp.begin(), boost::get(boost::vertex_index, g)));
    
    std::vector<std::vector<NodeID>> components(num);
    for (int i = 0; i < n; ++i) {
        components[comp[i]].push_back(bgl_to_id[i]);
    }
    return components;
}

template <typename GraphWrapper>
auto connected_components(const GraphWrapper& G) {
    using NodeID = typename GraphWrapper::NodeType;

    const auto& g = G.get_impl();
    const auto& bgl_to_id = G.get_bgl_to_id_map();

    const int n = static_cast<int>(boost::num_vertices(g));
    std::vector<int> comp(n);
    boost::connected_components(g, boost::make_iterator_property_map(comp.begin(), boost::get(boost::vertex_index, g)));

    lookup_map<NodeID, int> result;
    for (int i = 0; i < n; ++i) {
        result[bgl_to_id[i]] = comp[i];
    }
    return result;
}

template <typename GraphWrapper>
auto strongly_connected_component_groups(const GraphWrapper& G) {
    using NodeID = typename GraphWrapper::NodeType;
    auto& g = G.get_impl();
    auto& bgl_to_id = G.get_bgl_to_id_map();

    int n = boost::num_vertices(g);
    std::vector<int> comp(n);
    int num = boost::strong_components(g, boost::make_iterator_property_map(comp.begin(), boost::get(boost::vertex_index, g)));
    
    std::vector<std::vector<NodeID>> components(num);
    for (int i = 0; i < n; ++i) {
        components[comp[i]].push_back(bgl_to_id[i]);
    }
    return components;
}

template <typename GraphWrapper>
auto strong_components(const GraphWrapper& G) {
    using NodeID = typename GraphWrapper::NodeType;

    const auto& g = G.get_impl();
    const auto& bgl_to_id = G.get_bgl_to_id_map();

    const int n = static_cast<int>(boost::num_vertices(g));
    std::vector<int> comp(n);
    boost::strong_components(g, boost::make_iterator_property_map(comp.begin(), boost::get(boost::vertex_index, g)));

    lookup_map<NodeID, int> result;
    for (int i = 0; i < n; ++i) {
        result[bgl_to_id[i]] = comp[i];
    }
    return result;
}

template <typename GraphWrapper>
auto strong_component_roots(const GraphWrapper& G) {
    using NodeID = typename GraphWrapper::NodeType;

    const auto& g = G.get_impl();
    const auto& bgl_to_id = G.get_bgl_to_id_map();
    const int n = static_cast<int>(boost::num_vertices(g));

    std::vector<int> comp(n);
    std::vector<typename GraphWrapper::VertexDesc> roots(n);
    boost::strong_components(
        g,
        boost::make_iterator_property_map(comp.begin(), boost::get(boost::vertex_index, g)),
        boost::root_map(boost::make_iterator_property_map(roots.begin(), boost::get(boost::vertex_index, g)))
    );

    std::unordered_map<NodeID, NodeID> result;
    for (int i = 0; i < n; ++i) {
        result[bgl_to_id[i]] = bgl_to_id[roots[i]];
    }
    return result;
}

template <typename GraphWrapper>
auto connected_component_map(const GraphWrapper& G) {
    return connected_components(G);
}

template <typename GraphWrapper>
auto strongly_connected_components(const GraphWrapper& G) {
    return strongly_connected_component_groups(G);
}

template <typename GraphWrapper>
auto strongly_connected_component_map(const GraphWrapper& G) {
    return strong_components(G);
}

template <typename GraphWrapper>
auto strongly_connected_component_roots(const GraphWrapper& G) {
    return strong_component_roots(G);
}

template <typename GraphWrapper>
auto topological_sort(const GraphWrapper& G) {
    using NodeID = typename GraphWrapper::NodeType;

    std::vector<typename GraphWrapper::VertexDesc> rev_order;
    boost::topological_sort(G.get_impl(), std::back_inserter(rev_order));

    std::vector<NodeID> order;
    order.reserve(rev_order.size());
    for (auto it = rev_order.rbegin(); it != rev_order.rend(); ++it) {
        order.push_back(G.get_bgl_to_id_map()[*it]);
    }
    return order;
}

template <typename GraphWrapper>
requires(GraphWrapper::has_builtin_edge_weight)
auto kruskal_minimum_spanning_tree(const GraphWrapper& G) {
    using NodeID = typename GraphWrapper::NodeType;
    using EdgeDesc = typename GraphWrapper::EdgeDesc;

    std::vector<EdgeDesc> mst_edges;
    boost::kruskal_minimum_spanning_tree(G.get_impl(), std::back_inserter(mst_edges));

    std::vector<std::pair<NodeID, NodeID>> result;
    result.reserve(mst_edges.size());
    const auto& impl = G.get_impl();
    const auto& bgl_to_id = G.get_bgl_to_id_map();
    for (const auto& e : mst_edges) {
        result.emplace_back(bgl_to_id[boost::source(e, impl)], bgl_to_id[boost::target(e, impl)]);
    }
    return result;
}

template <typename GraphWrapper>
requires(GraphWrapper::has_builtin_edge_weight)
auto prim_minimum_spanning_tree(const GraphWrapper& G, const typename GraphWrapper::NodeType& root_id) {
    using NodeID = typename GraphWrapper::NodeType;
    using VertexDesc = typename GraphWrapper::VertexDesc;

    const auto& impl = G.get_impl();
    const auto& id_to_bgl = G.get_id_to_bgl_map();
    const auto& bgl_to_id = G.get_bgl_to_id_map();

    if (id_to_bgl.find(root_id) == id_to_bgl.end()) {
        throw std::runtime_error("Root node not found in graph.");
    }

    std::vector<VertexDesc> parent(boost::num_vertices(impl));
    boost::prim_minimum_spanning_tree(
        impl,
        boost::make_iterator_property_map(parent.begin(), boost::get(boost::vertex_index, impl)),
        boost::root_vertex(id_to_bgl.at(root_id))
    );

    std::unordered_map<NodeID, NodeID> result;
    for (size_t i = 0; i < parent.size(); ++i) {
        result[bgl_to_id[i]] = bgl_to_id[parent[i]];
    }
    return result;
}

template <typename GraphWrapper>
requires(GraphWrapper::has_builtin_edge_weight)
auto minimum_spanning_tree(const GraphWrapper& G) {
    return kruskal_minimum_spanning_tree(G);
}

template <typename GraphWrapper>
requires(GraphWrapper::has_builtin_edge_weight)
auto minimum_spanning_tree(const GraphWrapper& G, const typename GraphWrapper::NodeType& root_id) {
    return prim_minimum_spanning_tree(G, root_id);
}

template <typename GraphWrapper>
auto edmonds_karp_maximum_flow(const GraphWrapper& G, const typename GraphWrapper::NodeType& source_id, const typename GraphWrapper::NodeType& target_id, const std::string& capacity_attr = "capacity") {
    using NodeID = typename GraphWrapper::NodeType;

    if (!G.has_node(source_id) || !G.has_node(target_id)) {
        throw std::runtime_error("Source or target node not found in graph.");
    }

    using FlowTraits = boost::adjacency_list_traits<boost::vecS, boost::vecS, boost::directedS>;
    using FlowGraph = boost::adjacency_list<
        boost::vecS,
        boost::vecS,
        boost::directedS,
        boost::no_property,
        boost::property<
            boost::edge_capacity_t,
            long,
            boost::property<
                boost::edge_residual_capacity_t,
                long,
                boost::property<boost::edge_reverse_t, typename FlowTraits::edge_descriptor>
            >
        >
    >;

    using CapacityMap = typename boost::property_map<FlowGraph, boost::edge_capacity_t>::type;
    using ResidualMap = typename boost::property_map<FlowGraph, boost::edge_residual_capacity_t>::type;
    using ReverseMap = typename boost::property_map<FlowGraph, boost::edge_reverse_t>::type;
    using FlowEdgeDesc = typename boost::graph_traits<FlowGraph>::edge_descriptor;

    FlowGraph flow_graph;
    CapacityMap capacity = boost::get(boost::edge_capacity, flow_graph);
    ReverseMap reverse = boost::get(boost::edge_reverse, flow_graph);

    const auto nodes = G.nodes();
    std::unordered_map<NodeID, std::size_t> node_to_index;
    for (std::size_t i = 0; i < nodes.size(); ++i) {
        boost::add_vertex(flow_graph);
        node_to_index[nodes[i]] = i;
    }

    std::map<std::pair<NodeID, NodeID>, FlowEdgeDesc> original_edges;
    for (const auto& [u, v] : G.edge_pairs()) {
        auto [e, added] = boost::add_edge(node_to_index.at(u), node_to_index.at(v), flow_graph);
        auto [rev, rev_added] = boost::add_edge(node_to_index.at(v), node_to_index.at(u), flow_graph);
        (void)added;
        (void)rev_added;

        capacity[e] = static_cast<long>(G.get_edge_numeric_attr(u, v, capacity_attr));
        capacity[rev] = 0;
        reverse[e] = rev;
        reverse[rev] = e;
        original_edges[{u, v}] = e;
    }

    const long flow_value = boost::edmonds_karp_max_flow(
        flow_graph,
        node_to_index.at(source_id),
        node_to_index.at(target_id)
    );

    ResidualMap residual = boost::get(boost::edge_residual_capacity, flow_graph);

    MaximumFlowResult<NodeID> result;
    result.value = flow_value;
    for (const auto& [key, edge_desc] : original_edges) {
        result.flow[key] = capacity[edge_desc] - residual[edge_desc];
    }
    return result;
}

template <typename GraphWrapper>
auto push_relabel_maximum_flow_result(const GraphWrapper& G, const typename GraphWrapper::NodeType& source_id, const typename GraphWrapper::NodeType& target_id, const std::string& capacity_attr = "capacity") {
    using NodeID = typename GraphWrapper::NodeType;

    if (!G.has_node(source_id) || !G.has_node(target_id)) {
        throw std::runtime_error("Source or target node not found in graph.");
    }

    using FlowTraits = boost::adjacency_list_traits<boost::vecS, boost::vecS, boost::directedS>;
    using FlowGraph = boost::adjacency_list<
        boost::vecS,
        boost::vecS,
        boost::directedS,
        boost::no_property,
        boost::property<
            boost::edge_capacity_t,
            long,
            boost::property<
                boost::edge_residual_capacity_t,
                long,
                boost::property<boost::edge_reverse_t, typename FlowTraits::edge_descriptor>
            >
        >
    >;

    using CapacityMap = typename boost::property_map<FlowGraph, boost::edge_capacity_t>::type;
    using ResidualMap = typename boost::property_map<FlowGraph, boost::edge_residual_capacity_t>::type;
    using ReverseMap = typename boost::property_map<FlowGraph, boost::edge_reverse_t>::type;
    using FlowEdgeDesc = typename boost::graph_traits<FlowGraph>::edge_descriptor;

    FlowGraph flow_graph;
    CapacityMap capacity = boost::get(boost::edge_capacity, flow_graph);
    ReverseMap reverse = boost::get(boost::edge_reverse, flow_graph);

    const auto nodes = G.nodes();
    std::unordered_map<NodeID, std::size_t> node_to_index;
    for (std::size_t i = 0; i < nodes.size(); ++i) {
        boost::add_vertex(flow_graph);
        node_to_index[nodes[i]] = i;
    }

    std::map<std::pair<NodeID, NodeID>, FlowEdgeDesc> original_edges;
    for (const auto& [u, v] : G.edge_pairs()) {
        auto [e, added] = boost::add_edge(node_to_index.at(u), node_to_index.at(v), flow_graph);
        auto [rev, rev_added] = boost::add_edge(node_to_index.at(v), node_to_index.at(u), flow_graph);
        (void)added;
        (void)rev_added;

        capacity[e] = static_cast<long>(G.get_edge_numeric_attr(u, v, capacity_attr));
        capacity[rev] = 0;
        reverse[e] = rev;
        reverse[rev] = e;
        original_edges[{u, v}] = e;
    }

    const long flow_value = boost::push_relabel_max_flow(
        flow_graph,
        node_to_index.at(source_id),
        node_to_index.at(target_id)
    );

    ResidualMap residual = boost::get(boost::edge_residual_capacity, flow_graph);

    MaximumFlowResult<NodeID> result;
    result.value = flow_value;
    for (const auto& [key, edge_desc] : original_edges) {
        result.flow[key] = capacity[edge_desc] - residual[edge_desc];
    }
    return result;
}

template <typename GraphWrapper>
auto maximum_flow(const GraphWrapper& G, const typename GraphWrapper::NodeType& source_id, const typename GraphWrapper::NodeType& target_id, const std::string& capacity_attr = "capacity") {
    return edmonds_karp_maximum_flow(G, source_id, target_id, capacity_attr);
}

template <typename GraphWrapper>
auto minimum_cut(const GraphWrapper& G, const typename GraphWrapper::NodeType& source_id, const typename GraphWrapper::NodeType& target_id, const std::string& capacity_attr = "capacity") {
    using NodeID = typename GraphWrapper::NodeType;

    if (!G.has_node(source_id) || !G.has_node(target_id)) {
        throw std::runtime_error("Source or target node not found in graph.");
    }

    using FlowTraits = boost::adjacency_list_traits<boost::vecS, boost::vecS, boost::directedS>;
    using FlowGraph = boost::adjacency_list<
        boost::vecS,
        boost::vecS,
        boost::directedS,
        boost::no_property,
        boost::property<
            boost::edge_capacity_t,
            long,
            boost::property<
                boost::edge_residual_capacity_t,
                long,
                boost::property<boost::edge_reverse_t, typename FlowTraits::edge_descriptor>
            >
        >
    >;

    using CapacityMap = typename boost::property_map<FlowGraph, boost::edge_capacity_t>::type;
    using ResidualMap = typename boost::property_map<FlowGraph, boost::edge_residual_capacity_t>::type;
    using ReverseMap = typename boost::property_map<FlowGraph, boost::edge_reverse_t>::type;

    FlowGraph flow_graph;
    CapacityMap capacity = boost::get(boost::edge_capacity, flow_graph);
    ReverseMap reverse = boost::get(boost::edge_reverse, flow_graph);

    const auto nodes = G.nodes();
    std::unordered_map<NodeID, std::size_t> node_to_index;
    std::vector<NodeID> index_to_node;
    index_to_node.reserve(nodes.size());
    for (std::size_t i = 0; i < nodes.size(); ++i) {
        boost::add_vertex(flow_graph);
        node_to_index[nodes[i]] = i;
        index_to_node.push_back(nodes[i]);
    }

    for (const auto& [u, v, w] : G.edges()) {
        (void)w;
        auto [e, added] = boost::add_edge(node_to_index.at(u), node_to_index.at(v), flow_graph);
        auto [rev, rev_added] = boost::add_edge(node_to_index.at(v), node_to_index.at(u), flow_graph);
        (void)added;
        (void)rev_added;

        capacity[e] = static_cast<long>(G.get_edge_numeric_attr(u, v, capacity_attr));
        capacity[rev] = 0;
        reverse[e] = rev;
        reverse[rev] = e;
    }

    const auto source_index = node_to_index.at(source_id);
    const auto target_index = node_to_index.at(target_id);
    const long cut_value = boost::edmonds_karp_max_flow(flow_graph, source_index, target_index);

    ResidualMap residual = boost::get(boost::edge_residual_capacity, flow_graph);
    std::vector<bool> visited(nodes.size(), false);
    std::queue<std::size_t> q;
    visited[source_index] = true;
    q.push(source_index);

    while (!q.empty()) {
        const auto current = q.front();
        q.pop();
        for (auto [eit, eend] = boost::out_edges(current, flow_graph); eit != eend; ++eit) {
            const auto next = boost::target(*eit, flow_graph);
            if (!visited[next] && residual[*eit] > 0) {
                visited[next] = true;
                q.push(next);
            }
        }
    }

    MinimumCutResult<NodeID> result;
    result.value = cut_value;
    for (std::size_t i = 0; i < index_to_node.size(); ++i) {
        if (visited[i]) result.reachable.push_back(index_to_node[i]);
        else result.non_reachable.push_back(index_to_node[i]);
    }

    for (const auto& [u, v] : G.edge_pairs()) {
        if (visited[node_to_index.at(u)] && !visited[node_to_index.at(v)]) {
            result.cut_edges.emplace_back(u, v);
        }
    }

    return result;
}

template <typename GraphWrapper>
auto max_flow_min_cost_cycle_canceling(const GraphWrapper& G, const typename GraphWrapper::NodeType& source_id, const typename GraphWrapper::NodeType& target_id, const std::string& capacity_attr = "capacity", const std::string& weight_attr = "weight") {
    using NodeID = typename GraphWrapper::NodeType;

    if (!G.has_node(source_id) || !G.has_node(target_id)) {
        throw std::runtime_error("Source or target node not found in graph.");
    }

    using FlowTraits = boost::adjacency_list_traits<boost::vecS, boost::vecS, boost::directedS>;
    using FlowGraph = boost::adjacency_list<
        boost::vecS,
        boost::vecS,
        boost::directedS,
        boost::no_property,
        boost::property<
            boost::edge_weight_t,
            long,
            boost::property<
                boost::edge_capacity_t,
                long,
                boost::property<
                    boost::edge_residual_capacity_t,
                    long,
                    boost::property<boost::edge_reverse_t, typename FlowTraits::edge_descriptor>
                >
            >
        >
    >;

    using WeightMap = typename boost::property_map<FlowGraph, boost::edge_weight_t>::type;
    using CapacityMap = typename boost::property_map<FlowGraph, boost::edge_capacity_t>::type;
    using ResidualMap = typename boost::property_map<FlowGraph, boost::edge_residual_capacity_t>::type;
    using ReverseMap = typename boost::property_map<FlowGraph, boost::edge_reverse_t>::type;
    using FlowEdgeDesc = typename boost::graph_traits<FlowGraph>::edge_descriptor;

    FlowGraph flow_graph;
    WeightMap weight = boost::get(boost::edge_weight, flow_graph);
    CapacityMap capacity = boost::get(boost::edge_capacity, flow_graph);
    ReverseMap reverse = boost::get(boost::edge_reverse, flow_graph);

    const auto nodes = G.nodes();
    std::unordered_map<NodeID, std::size_t> node_to_index;
    for (std::size_t i = 0; i < nodes.size(); ++i) {
        boost::add_vertex(flow_graph);
        node_to_index[nodes[i]] = i;
    }

    std::map<std::pair<NodeID, NodeID>, FlowEdgeDesc> original_edges;
    for (const auto& [u, v] : G.edge_pairs()) {
        auto [e, added] = boost::add_edge(node_to_index.at(u), node_to_index.at(v), flow_graph);
        auto [rev, rev_added] = boost::add_edge(node_to_index.at(v), node_to_index.at(u), flow_graph);
        (void)added;
        (void)rev_added;

        weight[e] = static_cast<long>(G.get_edge_numeric_attr(u, v, weight_attr));
        weight[rev] = -weight[e];
        capacity[e] = static_cast<long>(G.get_edge_numeric_attr(u, v, capacity_attr));
        capacity[rev] = 0;
        reverse[e] = rev;
        reverse[rev] = e;
        original_edges[{u, v}] = e;
    }

    boost::push_relabel_max_flow(
        flow_graph,
        node_to_index.at(source_id),
        node_to_index.at(target_id)
    );
    boost::cycle_canceling(flow_graph);
    const long cost = boost::find_flow_cost(flow_graph);

    ResidualMap residual = boost::get(boost::edge_residual_capacity, flow_graph);
    MinCostMaxFlowResult<NodeID> result;
    result.cost = cost;
    for (const auto& [key, edge_desc] : original_edges) {
        result.edge_flows[key] = capacity[edge_desc] - residual[edge_desc];
        if (key.first == source_id) {
            result.flow += result.edge_flows[key];
        }
    }
    return result;
}

template <typename GraphWrapper>
long push_relabel_maximum_flow(const GraphWrapper& G, const typename GraphWrapper::NodeType& source_id, const typename GraphWrapper::NodeType& target_id, const std::string& capacity_attr = "capacity", const std::string& weight_attr = "weight") {
    using NodeID = typename GraphWrapper::NodeType;

    if (!G.has_node(source_id) || !G.has_node(target_id)) {
        throw std::runtime_error("Source or target node not found in graph.");
    }

    auto state = std::make_unique<detail::MinCostFlowState<NodeID>>();
    state->source_id = source_id;
    state->target_id = target_id;

    const auto nodes = G.nodes();
    for (std::size_t i = 0; i < nodes.size(); ++i) {
        boost::add_vertex(state->flow_graph);
        state->node_to_index[nodes[i]] = i;
    }

    for (const auto& [u, v] : G.edge_pairs()) {
        auto [e, added] = boost::add_edge(state->node_to_index.at(u), state->node_to_index.at(v), state->flow_graph);
        auto [rev, rev_added] = boost::add_edge(state->node_to_index.at(v), state->node_to_index.at(u), state->flow_graph);
        (void)added;
        (void)rev_added;

        state->weight[e] = static_cast<long>(G.get_edge_numeric_attr(u, v, weight_attr));
        state->weight[rev] = -state->weight[e];
        state->capacity[e] = static_cast<long>(G.get_edge_numeric_attr(u, v, capacity_attr));
        state->capacity[rev] = 0;
        state->reverse[e] = rev;
        state->reverse[rev] = e;
        state->original_edges[{u, v}] = e;
    }

    state->value = boost::push_relabel_max_flow(
        state->flow_graph,
        state->node_to_index.at(source_id),
        state->node_to_index.at(target_id)
    );

    auto& cache = detail::min_cost_flow_cache<GraphWrapper>();
    cache[static_cast<const void*>(&G)] = std::move(state);
    return cache.at(static_cast<const void*>(&G))->value;
}

template <typename GraphWrapper>
auto cycle_canceling(const GraphWrapper& G, const std::string& weight_attr = "weight") {
    auto& cache = detail::min_cost_flow_cache<GraphWrapper>();
    auto it = cache.find(static_cast<const void*>(&G));

    if (it == cache.end()) {
        throw std::runtime_error("Cycle-canceling state unavailable: run push_relabel_maximum_flow(...) first.");
    }

    auto& state = *it->second;

    for (const auto& [key, edge_desc] : state.original_edges) {
        state.weight[edge_desc] = static_cast<long>(G.get_edge_numeric_attr(key.first, key.second, weight_attr));
        const auto rev = state.reverse[edge_desc];
        state.weight[rev] = -state.weight[edge_desc];
    }

    boost::cycle_canceling(state.flow_graph);
    state.cost = boost::find_flow_cost(state.flow_graph);
    return state.cost;
}

template <typename GraphWrapper>
auto max_flow_min_cost_successive_shortest_path(const GraphWrapper& G, const typename GraphWrapper::NodeType& source_id, const typename GraphWrapper::NodeType& target_id, const std::string& capacity_attr = "capacity", const std::string& weight_attr = "weight") {
    using NodeID = typename GraphWrapper::NodeType;

    if (!G.has_node(source_id) || !G.has_node(target_id)) {
        throw std::runtime_error("Source or target node not found in graph.");
    }

    using FlowTraits = boost::adjacency_list_traits<boost::vecS, boost::vecS, boost::directedS>;
    using FlowGraph = boost::adjacency_list<
        boost::vecS,
        boost::vecS,
        boost::directedS,
        boost::no_property,
        boost::property<
            boost::edge_weight_t,
            long,
            boost::property<
                boost::edge_capacity_t,
                long,
                boost::property<
                    boost::edge_residual_capacity_t,
                    long,
                    boost::property<boost::edge_reverse_t, typename FlowTraits::edge_descriptor>
                >
            >
        >
    >;

    using WeightMap = typename boost::property_map<FlowGraph, boost::edge_weight_t>::type;
    using CapacityMap = typename boost::property_map<FlowGraph, boost::edge_capacity_t>::type;
    using ResidualMap = typename boost::property_map<FlowGraph, boost::edge_residual_capacity_t>::type;
    using ReverseMap = typename boost::property_map<FlowGraph, boost::edge_reverse_t>::type;
    using FlowEdgeDesc = typename boost::graph_traits<FlowGraph>::edge_descriptor;

    FlowGraph flow_graph;
    WeightMap weight = boost::get(boost::edge_weight, flow_graph);
    CapacityMap capacity = boost::get(boost::edge_capacity, flow_graph);
    ReverseMap reverse = boost::get(boost::edge_reverse, flow_graph);

    const auto nodes = G.nodes();
    std::unordered_map<NodeID, std::size_t> node_to_index;
    for (std::size_t i = 0; i < nodes.size(); ++i) {
        boost::add_vertex(flow_graph);
        node_to_index[nodes[i]] = i;
    }

    std::map<std::pair<NodeID, NodeID>, FlowEdgeDesc> original_edges;
    for (const auto& [u, v] : G.edge_pairs()) {
        auto [e, added] = boost::add_edge(node_to_index.at(u), node_to_index.at(v), flow_graph);
        auto [rev, rev_added] = boost::add_edge(node_to_index.at(v), node_to_index.at(u), flow_graph);
        (void)added;
        (void)rev_added;

        weight[e] = static_cast<long>(G.get_edge_numeric_attr(u, v, weight_attr));
        weight[rev] = -weight[e];
        capacity[e] = static_cast<long>(G.get_edge_numeric_attr(u, v, capacity_attr));
        capacity[rev] = 0;
        reverse[e] = rev;
        reverse[rev] = e;
        original_edges[{u, v}] = e;
    }

    boost::successive_shortest_path_nonnegative_weights(
        flow_graph,
        node_to_index.at(source_id),
        node_to_index.at(target_id)
    );

    ResidualMap residual = boost::get(boost::edge_residual_capacity, flow_graph);
    long flow_value = 0;
    for (auto [eit, eend] = boost::out_edges(node_to_index.at(source_id), flow_graph); eit != eend; ++eit) {
        flow_value += capacity[*eit] - residual[*eit];
    }

    const long cost = boost::find_flow_cost(flow_graph);

    MinCostMaxFlowResult<NodeID> result;
    result.flow = flow_value;
    result.cost = cost;
    for (const auto& [key, edge_desc] : original_edges) {
        result.edge_flows[key] = capacity[edge_desc] - residual[edge_desc];
    }
    return result;
}
template <typename GraphWrapper>
auto max_flow_min_cost(const GraphWrapper& G, const typename GraphWrapper::NodeType& source_id, const typename GraphWrapper::NodeType& target_id, const std::string& capacity_attr = "capacity", const std::string& weight_attr = "weight") {
    return max_flow_min_cost_cycle_canceling(G, source_id, target_id, capacity_attr, weight_attr);
}

inline int to_2sat_vertex_id(int literal) {
    return (literal > 0) ? (2 * literal - 2) : (-2 * literal - 1);
}

inline bool two_sat_satisfiable(int num_variables, const std::vector<std::pair<int, int>>& clauses) {
    using SatGraph = boost::adjacency_list<boost::vecS, boost::vecS, boost::directedS>;

    SatGraph g(2 * num_variables);
    for (const auto& [x, y] : clauses) {
        boost::add_edge(to_2sat_vertex_id(-x), to_2sat_vertex_id(y), g);
        boost::add_edge(to_2sat_vertex_id(-y), to_2sat_vertex_id(x), g);
    }

    std::vector<int> comp(boost::num_vertices(g));
    boost::strong_components(g, boost::make_iterator_property_map(comp.begin(), boost::get(boost::vertex_index, g)));

    for (int i = 1; i <= num_variables; ++i) {
        if (comp[to_2sat_vertex_id(i)] == comp[to_2sat_vertex_id(-i)]) {
            return false;
        }
    }
    return true;
}

template <typename GraphWrapper>
auto degree_centrality(const GraphWrapper& G) {
    using NodeID = typename GraphWrapper::NodeType;

    const auto& g = G.get_impl();
    const auto& bgl_to_id = G.get_bgl_to_id_map();
    const auto node_count = boost::num_vertices(g);

    std::unordered_map<NodeID, double> centrality;
    if (node_count == 0) {
        return centrality;
    }

    for (auto [v, vend] = boost::vertices(g); v != vend; ++v) {
        centrality[bgl_to_id[*v]] = 0.0;
    }

    if (node_count <= 1) {
        return centrality;
    }

    const double scale = 1.0 / static_cast<double>(node_count - 1);
    for (auto [v, vend] = boost::vertices(g); v != vend; ++v) {
        double degree = 0.0;
        if constexpr (GraphWrapper::is_directed) {
            degree = static_cast<double>(boost::in_degree(*v, g) + boost::out_degree(*v, g));
        } else {
            degree = static_cast<double>(boost::degree(*v, g));
        }
        centrality[bgl_to_id[*v]] = degree * scale;
    }

    return centrality;
}

} // namespace nxpp

#endif // NXPP_MODULAR_COMPONENTS_HPP
