#ifndef NXPP_MODULAR_GRAPH_HPP
#define NXPP_MODULAR_GRAPH_HPP

// Generated from include/nxpp.hpp by scripts/sync_modular_headers.py.
// Do not edit this file directly: keep include/nxpp.hpp as the single source of truth.

#include "base.hpp"

namespace nxpp {

template <typename NodeID = std::string, typename EdgeWeight = double, bool Directed = false, bool Multi = false, bool Weighted = true>
class Graph {
public:
    using NodeType = NodeID;
    using EdgeWeightType = EdgeWeight;
    using DirectedSelector = typename std::conditional<Directed, boost::bidirectionalS, boost::undirectedS>::type;
    using EdgeProperty = typename std::conditional<
        Weighted,
        boost::property<boost::edge_weight_t, EdgeWeight, boost::property<boost::edge_index_t, std::size_t>>,
        boost::property<boost::edge_index_t, std::size_t>
    >::type;
    using GraphType = boost::adjacency_list<boost::vecS, boost::vecS, DirectedSelector,
                                            boost::no_property, EdgeProperty>;
    using VertexDesc = typename boost::graph_traits<GraphType>::vertex_descriptor;
    using EdgeDesc = typename boost::graph_traits<GraphType>::edge_descriptor;
    using WeightMap = typename built_in_weight_traits<GraphType, Weighted>::map_type;
    using EdgeIdMap = typename boost::property_map<GraphType, boost::edge_index_t>::type;
    static constexpr bool is_directed = Directed;
    static constexpr bool has_builtin_edge_weight = Weighted;

private:
    GraphType g;
    WeightMap weight_map;
    EdgeIdMap edge_id_map;
    std::unordered_map<NodeID, VertexDesc> id_to_bgl;
    std::vector<NodeID> bgl_to_id;
    std::size_t next_edge_id = 0;

public:
    std::unordered_map<NodeID, std::unordered_map<std::string, std::any>> node_properties;
    std::unordered_map<std::size_t, std::unordered_map<std::string, std::any>> edge_properties;

private:
    using EdgeAttrMap = std::unordered_map<std::string, std::any>;

    VertexDesc get_or_create_vertex(const NodeID& id) {
        auto it = id_to_bgl.find(id);
        if (it != id_to_bgl.end()) {
            return it->second;
        }
        VertexDesc v = boost::add_vertex(g);
        id_to_bgl[id] = v;
        if (v >= bgl_to_id.size()) {
            bgl_to_id.resize(v + 1);
        }
        bgl_to_id[v] = id;
        return v;
    }

    std::size_t get_edge_id(EdgeDesc e) const {
        return boost::get(edge_id_map, e);
    }

    void erase_incident_edge_properties(VertexDesc v) {
        std::vector<std::size_t> edge_ids;
        for (auto [e, eend] = boost::edges(g); e != eend; ++e) {
            if (boost::source(*e, g) == v || boost::target(*e, g) == v) {
                edge_ids.push_back(get_edge_id(*e));
            }
        }
        for (auto edge_id : edge_ids) {
            edge_properties.erase(edge_id);
        }
    }

    void assign_edge_attrs(EdgeDesc e, const EdgeAttrMap& attrs) {
        auto& edge_attr_map = edge_properties[get_edge_id(e)];
        for (const auto& [key, value] : attrs) {
            edge_attr_map[key] = value;
        }
    }

    void assign_edge_attrs(EdgeDesc e, std::initializer_list<std::pair<std::string, std::any>> attrs) {
        auto& edge_attr_map = edge_properties[get_edge_id(e)];
        for (const auto& [key, value] : attrs) {
            edge_attr_map[key] = value;
        }
    }

    void assign_edge_attr(EdgeDesc e, const std::pair<std::string, std::any>& attr) {
        edge_properties[get_edge_id(e)][attr.first] = attr.second;
    }

public:
    Graph() : g(), weight_map(built_in_weight_traits<GraphType, Weighted>::get(g)), edge_id_map(boost::get(boost::edge_index, g)) {}

    void add_node(const NodeID& id) {
        get_or_create_vertex(id);
    }

    void add_nodes_from(const std::vector<NodeID>& nodes) {
        for (const auto& n : nodes) {
            add_node(n);
        }
    }

    EdgeDesc get_edge_desc(const NodeID& u, const NodeID& v) const {
        auto it_u = id_to_bgl.find(u);
        auto it_v = id_to_bgl.find(v);
        if (it_u == id_to_bgl.end() || it_v == id_to_bgl.end()) throw std::runtime_error("Node not found");
        auto [e, exists] = boost::edge(it_u->second, it_v->second, g);
        if (!exists) throw std::runtime_error("Edge not found");
        return e;
    }

    bool has_edge(const NodeID& u, const NodeID& v) const {
        auto it_u = id_to_bgl.find(u);
        auto it_v = id_to_bgl.find(v);
        if (it_u == id_to_bgl.end() || it_v == id_to_bgl.end()) return false;
        auto [e, exists] = boost::edge(it_u->second, it_v->second, g);
        return exists;
    }

    template <bool W = Weighted>
    requires(W)
    void add_edge(const NodeID& u, const NodeID& v, EdgeWeight w = 1.0) {
        VertexDesc bu = get_or_create_vertex(u);
        VertexDesc bv = get_or_create_vertex(v);
        
        if constexpr (!Multi) {
            auto [e, exists] = boost::edge(bu, bv, g);
            if (exists) {
                weight_map[e] = w;
                return;
            }
        }
        
        auto [e, added] = boost::add_edge(bu, bv, g);
        weight_map[e] = w;
        edge_id_map[e] = next_edge_id++;
    }

    template <bool W = Weighted>
    requires(!W)
    void add_edge(const NodeID& u, const NodeID& v) {
        VertexDesc bu = get_or_create_vertex(u);
        VertexDesc bv = get_or_create_vertex(v);

        if constexpr (!Multi) {
            auto [e, exists] = boost::edge(bu, bv, g);
            if (exists) {
                return;
            }
        }

        auto [e, added] = boost::add_edge(bu, bv, g);
        (void)added;
        edge_id_map[e] = next_edge_id++;
    }

    template <bool W = Weighted>
    requires(W)
    void add_edge(const NodeID& u, const NodeID& v, EdgeWeight w, const EdgeAttrMap& attrs) {
        add_edge(u, v, w);
        assign_edge_attrs(get_edge_desc(u, v), attrs);
    }

    void add_edge(const NodeID& u, const NodeID& v, const EdgeAttrMap& attrs) {
        if constexpr (Weighted) {
            add_edge(u, v, static_cast<EdgeWeight>(1.0), attrs);
        } else {
            add_edge(u, v);
            assign_edge_attrs(get_edge_desc(u, v), attrs);
        }
    }

    template <bool W = Weighted>
    requires(W)
    void add_edge(const NodeID& u, const NodeID& v, EdgeWeight w, const std::pair<std::string, std::any>& attr) {
        add_edge(u, v, w);
        assign_edge_attr(get_edge_desc(u, v), attr);
    }

    void add_edge(const NodeID& u, const NodeID& v, const std::pair<std::string, std::any>& attr) {
        if constexpr (Weighted) {
            add_edge(u, v, static_cast<EdgeWeight>(1.0), attr);
        } else {
            add_edge(u, v);
            assign_edge_attr(get_edge_desc(u, v), attr);
        }
    }

    template <bool W = Weighted>
    requires(W)
    void add_edge(const NodeID& u, const NodeID& v, EdgeWeight w, std::initializer_list<std::pair<std::string, std::any>> attrs) {
        add_edge(u, v, w);
        assign_edge_attrs(get_edge_desc(u, v), attrs);
    }

    void add_edge(const NodeID& u, const NodeID& v, std::initializer_list<std::pair<std::string, std::any>> attrs) {
        if constexpr (Weighted) {
            add_edge(u, v, static_cast<EdgeWeight>(1.0), attrs);
        } else {
            add_edge(u, v);
            assign_edge_attrs(get_edge_desc(u, v), attrs);
        }
    }

    template <bool W = Weighted>
    requires(W)
    void add_edges_from(const std::vector<std::tuple<NodeID, NodeID, EdgeWeight>>& edges) {
        for (const auto& edge : edges) {
            add_edge(std::get<0>(edge), std::get<1>(edge), std::get<2>(edge));
        }
    }

    void add_edges_from(const std::vector<std::pair<NodeID, NodeID>>& edges) {
        for (const auto& edge : edges) {
            add_edge(edge.first, edge.second);
        }
    }

    void clear() {
        g = GraphType();
        id_to_bgl.clear();
        bgl_to_id.clear();
        node_properties.clear();
        edge_properties.clear();
        weight_map = built_in_weight_traits<GraphType, Weighted>::get(g);
        edge_id_map = boost::get(boost::edge_index, g);
        next_edge_id = 0;
    }

    void remove_edge(const NodeID& u, const NodeID& v) {
        auto it_u = id_to_bgl.find(u);
        auto it_v = id_to_bgl.find(v);
        if (it_u == id_to_bgl.end() || it_v == id_to_bgl.end()) {
            throw std::runtime_error("NetworkXError: The node is not in the graph.");
        }
        auto [e, exists] = boost::edge(it_u->second, it_v->second, g);
        if (!exists) {
            throw std::runtime_error("NetworkXError: The edge is not in the graph.");
        }
        edge_properties.erase(get_edge_id(e));
        boost::remove_edge(it_u->second, it_v->second, g);
    }

    void remove_node(const NodeID& u) {
        auto it = id_to_bgl.find(u);
        if (it == id_to_bgl.end()) {
            throw std::runtime_error("NetworkXError: The node is not in the graph.");
        }
        VertexDesc v = it->second;

        erase_incident_edge_properties(v);
        boost::clear_vertex(v, g);
        boost::remove_vertex(v, g);
        
        id_to_bgl.erase(it);
        node_properties.erase(u);

        // When using vecS, remove_vertex invalidates all descriptors > v
        // because all subsequent vertices are shifted down by 1.
        // We must re-sync all NodeID -> index mappings for shifted vertices.
        bgl_to_id.erase(bgl_to_id.begin() + v);
        
        // Full re-sync of the ID to BGL map
        for (size_t i = 0; i < bgl_to_id.size(); ++i) {
            id_to_bgl[bgl_to_id[i]] = (VertexDesc)i;
        }
    }

    std::vector<NodeID> neighbors(const NodeID& u) const {
        auto it = id_to_bgl.find(u);
        if (it == id_to_bgl.end()) {
            throw std::runtime_error("NetworkXError: The node is not in the graph.");
        }
        std::vector<NodeID> res;
        for (auto [e, eend] = boost::out_edges(it->second, g); e != eend; ++e) {
            res.push_back(bgl_to_id[boost::target(*e, g)]);
        }
        return res;
    }

    std::vector<NodeID> successors(const NodeID& u) const {
        return neighbors(u);
    }

    std::vector<NodeID> predecessors(const NodeID& u) const {
        auto it = id_to_bgl.find(u);
        if (it == id_to_bgl.end()) {
            throw std::runtime_error("NetworkXError: The node is not in the graph.");
        }

        std::vector<NodeID> res;
        if constexpr (Directed) {
            for (auto [e, eend] = boost::in_edges(it->second, g); e != eend; ++e) {
                res.push_back(bgl_to_id[boost::source(*e, g)]);
            }
        } else {
            for (auto [e, eend] = boost::out_edges(it->second, g); e != eend; ++e) {
                res.push_back(bgl_to_id[boost::target(*e, g)]);
            }
        }
        return res;
    }

    bool has_node(const NodeID& u) const {
        return id_to_bgl.find(u) != id_to_bgl.end();
    }

    bool has_node_attr(const NodeID& u, const std::string& key) const {
        auto node_it = node_properties.find(u);
        if (node_it == node_properties.end()) {
            return false;
        }
        return node_it->second.find(key) != node_it->second.end();
    }

    bool has_edge_attr(const NodeID& u, const NodeID& v, const std::string& key) const {
        if (!has_edge(u, v)) {
            return false;
        }
        auto e = get_edge_desc(u, v);
        auto edge_it = edge_properties.find(get_edge_id(e));
        if (edge_it == edge_properties.end()) {
            return false;
        }
        return edge_it->second.find(key) != edge_it->second.end();
    }

    template <typename T>
    T get_node_attr(const NodeID& u, const std::string& key) const {
        auto node_it = node_properties.find(u);
        if (node_it == node_properties.end()) {
            throw std::runtime_error("Node attribute lookup failed: node has no attributes.");
        }
        auto attr_it = node_it->second.find(key);
        if (attr_it == node_it->second.end()) {
            throw std::runtime_error("Node attribute lookup failed: key not found.");
        }
        try {
            return std::any_cast<T>(attr_it->second);
        } catch (const std::bad_any_cast&) {
            throw std::runtime_error("Node attribute lookup failed: stored type does not match requested type.");
        }
    }

    template <typename T>
    T get_edge_attr(const NodeID& u, const NodeID& v, const std::string& key) const {
        auto e = get_edge_desc(u, v);
        auto edge_it = edge_properties.find(get_edge_id(e));
        if (edge_it == edge_properties.end()) {
            throw std::runtime_error("Edge attribute lookup failed: edge has no attributes.");
        }
        auto attr_it = edge_it->second.find(key);
        if (attr_it == edge_it->second.end()) {
            throw std::runtime_error("Edge attribute lookup failed: key not found.");
        }
        try {
            return std::any_cast<T>(attr_it->second);
        } catch (const std::bad_any_cast&) {
            throw std::runtime_error("Edge attribute lookup failed: stored type does not match requested type.");
        }
    }

    template <typename T>
    std::optional<T> try_get_node_attr(const NodeID& u, const std::string& key) const {
        auto node_it = node_properties.find(u);
        if (node_it == node_properties.end()) {
            return std::nullopt;
        }
        auto attr_it = node_it->second.find(key);
        if (attr_it == node_it->second.end()) {
            return std::nullopt;
        }
        if (const auto* value = std::any_cast<T>(&(attr_it->second))) {
            return *value;
        }
        return std::nullopt;
    }

    template <typename T>
    std::optional<T> try_get_edge_attr(const NodeID& u, const NodeID& v, const std::string& key) const {
        if (!has_edge(u, v)) {
            return std::nullopt;
        }
        auto e = get_edge_desc(u, v);
        auto edge_it = edge_properties.find(get_edge_id(e));
        if (edge_it == edge_properties.end()) {
            return std::nullopt;
        }
        auto attr_it = edge_it->second.find(key);
        if (attr_it == edge_it->second.end()) {
            return std::nullopt;
        }
        if (const auto* value = std::any_cast<T>(&(attr_it->second))) {
            return *value;
        }
        return std::nullopt;
    }

    double get_edge_numeric_attr(const NodeID& u, const NodeID& v, const std::string& key) const {
        if (key == "weight") {
            if constexpr (Weighted) {
                return static_cast<double>(get_edge_weight(u, v));
            } else {
                throw std::runtime_error("Edge attribute lookup failed: graph has no built-in edge weight.");
            }
        }

        auto e = get_edge_desc(u, v);
        auto edge_it = edge_properties.find(get_edge_id(e));
        if (edge_it == edge_properties.end()) {
            throw std::runtime_error("Edge attribute lookup failed: edge has no attributes.");
        }
        auto attr_it = edge_it->second.find(key);
        if (attr_it == edge_it->second.end()) {
            throw std::runtime_error("Edge attribute lookup failed: key not found.");
        }

        const auto& value = attr_it->second;
        if (const auto* vptr = std::any_cast<int>(&value)) return static_cast<double>(*vptr);
        if (const auto* vptr = std::any_cast<long>(&value)) return static_cast<double>(*vptr);
        if (const auto* vptr = std::any_cast<long long>(&value)) return static_cast<double>(*vptr);
        if (const auto* vptr = std::any_cast<float>(&value)) return static_cast<double>(*vptr);
        if (const auto* vptr = std::any_cast<double>(&value)) return *vptr;

        throw std::runtime_error("Edge attribute lookup failed: stored value is not numeric.");
    }

    template <bool W = Weighted>
    requires(W)
    EdgeWeight get_edge_weight(const NodeID& u, const NodeID& v) const {
        auto it_u = id_to_bgl.find(u);
        auto it_v = id_to_bgl.find(v);
        if (it_u == id_to_bgl.end() || it_v == id_to_bgl.end()) throw std::runtime_error("Node not found in graph");
        auto [e, exists] = boost::edge(it_u->second, it_v->second, g);
        if (!exists) throw std::runtime_error("Edge not found in graph");
        return weight_map[e];
    }

    std::vector<NodeID> nodes() const {
        std::vector<NodeID> res;
        for (auto [v, vend] = boost::vertices(g); v != vend; ++v) {
            res.push_back(bgl_to_id[*v]);
        }
        return res;
    }

    auto edges() const {
        if constexpr (Weighted) {
            std::vector<std::tuple<NodeID, NodeID, EdgeWeight>> res;
            for (auto [e, eend] = boost::edges(g); e != eend; ++e) {
                NodeID source_id = bgl_to_id[boost::source(*e, g)];
                NodeID target_id = bgl_to_id[boost::target(*e, g)];
                res.emplace_back(source_id, target_id, weight_map[*e]);
            }
            return res;
        } else {
            std::vector<std::pair<NodeID, NodeID>> res;
            for (auto [e, eend] = boost::edges(g); e != eend; ++e) {
                NodeID source_id = bgl_to_id[boost::source(*e, g)];
                NodeID target_id = bgl_to_id[boost::target(*e, g)];
                res.emplace_back(source_id, target_id);
            }
            return res;
        }
    }

    std::vector<std::pair<NodeID, NodeID>> edge_pairs() const {
        std::vector<std::pair<NodeID, NodeID>> res;
        for (auto [e, eend] = boost::edges(g); e != eend; ++e) {
            NodeID source_id = bgl_to_id[boost::source(*e, g)];
            NodeID target_id = bgl_to_id[boost::target(*e, g)];
            res.emplace_back(source_id, target_id);
        }
        return res;
    }

    // Accessors for BGL algorithms
    const GraphType& get_impl() const { return g; }
    const std::vector<NodeID>& get_bgl_to_id_map() const { return bgl_to_id; }
    const std::unordered_map<NodeID, VertexDesc>& get_id_to_bgl_map() const { return id_to_bgl; }

    // Proxy Pattern per simulare G[u][v] = weight
    struct EdgeAttrProxy {
        Graph* graph;
        NodeID u, v;
        std::string key;

        template <typename T>
        EdgeAttrProxy& operator=(const T& val) {
            if (!graph->has_edge(u, v)) {
                if constexpr (Weighted) graph->add_edge(u, v, static_cast<EdgeWeight>(1.0));
                else graph->add_edge(u, v);
            }
            auto e = graph->get_edge_desc(u, v);
            graph->edge_properties[graph->get_edge_id(e)][key] = std::any(val);
            return *this;
        }

        template <typename T>
        operator T() const {
            return graph->template get_edge_attr<T>(u, v, key);
        }
    };

    class EdgeProxy {
        Graph* graph;
        NodeID u, v;
    public:
        EdgeProxy(Graph* g, NodeID u, NodeID v) : graph(g), u(u), v(v) {}
        
        template <bool W = Weighted>
        requires(W)
        EdgeProxy& operator=(EdgeWeight w) {
            graph->add_edge(u, v, w);
            return *this;
        }

        template <bool W = Weighted>
        requires(W)
        operator EdgeWeight() const {
            return graph->get_edge_weight(u, v);
        }

        EdgeAttrProxy operator[](const std::string& key) {
            return {graph, u, v, key};
        }

        EdgeAttrProxy operator[](const char* key) {
            return {graph, u, v, std::string(key)};
        }
    };

    struct NodeAttrProxy {
        Graph* graph;
        NodeID u;
        std::string key;

        template <typename T>
        NodeAttrProxy& operator=(const T& val) {
            if (!graph->has_node(u)) graph->add_node(u);
            graph->node_properties[u][key] = std::any(val);
            return *this;
        }

        template <typename T>
        operator T() const {
            return graph->template get_node_attr<T>(u, key);
        }
    };

    class NodeProxy {
        Graph* graph;
        NodeID u;
    public:
        NodeProxy(Graph* g, NodeID u) : graph(g), u(u) {}
        
        EdgeProxy operator[](const NodeID& v) {
            return EdgeProxy(graph, u, v);
        }
    };

    class NodeAttrBaseProxy {
        Graph* graph;
        NodeID u;
    public:
        NodeAttrBaseProxy(Graph* g, NodeID u) : graph(g), u(u) {}
        
        NodeAttrProxy operator[](const std::string& key) {
            return {graph, u, key};
        }

        NodeAttrProxy operator[](const char* key) {
            return {graph, u, std::string(key)};
        }
    };

    NodeProxy operator[](const NodeID& u) {
        if (!has_node(u)) {
            add_node(u);
        }
        return NodeProxy(this, u);
    }

    NodeAttrBaseProxy node(const NodeID& u) {
        if (!has_node(u) && !Multi) add_node(u);
        else if (!has_node(u)) add_node(u);
        return NodeAttrBaseProxy(this, u);
    }
};

} // namespace nxpp

#endif // NXPP_MODULAR_GRAPH_HPP
