#ifndef NXPP_MODULAR_HPP
#define NXPP_MODULAR_HPP

// Generated from include/nxpp.hpp by scripts/sync_modular_headers.py.
// Do not edit this file directly: keep include/nxpp.hpp as the single source of truth.

#include "base.hpp"
#include "graph.hpp"
#include "generators.hpp"
#include "types.hpp"
#include "traversals.hpp"
#include "shortest_paths.hpp"
#include "components.hpp"

#endif // NXPP_MODULAR_HPP
