#ifndef NXPP_MODULAR_SHORTEST_PATHS_HPP
#define NXPP_MODULAR_SHORTEST_PATHS_HPP

// Generated from include/nxpp.hpp by scripts/sync_modular_headers.py.
// Do not edit this file directly: keep include/nxpp.hpp as the single source of truth.

#include "traversals.hpp"

namespace nxpp {

template <typename GraphWrapper>
auto shortest_path(const GraphWrapper& G, const typename GraphWrapper::NodeType& source_id, const typename GraphWrapper::NodeType& target_id) {
    using NodeID = typename GraphWrapper::NodeType;
    using VertexDesc = typename GraphWrapper::VertexDesc;

    const auto& g = G.get_impl();
    const auto& id_to_bgl = G.get_id_to_bgl_map();
    const auto& bgl_to_id = G.get_bgl_to_id_map();

    if (id_to_bgl.find(source_id) == id_to_bgl.end() || id_to_bgl.find(target_id) == id_to_bgl.end()) {
        throw std::runtime_error("Source or target node not found in graph.");
    }

    VertexDesc source = id_to_bgl.at(source_id);
    VertexDesc target = id_to_bgl.at(target_id);

    if (source == target) {
        return std::vector<NodeID>{source_id};
    }

    const size_t n = boost::num_vertices(g);
    std::vector<bool> visited(n, false);
    std::vector<VertexDesc> pred(n);
    std::queue<VertexDesc> q;

    for (size_t i = 0; i < n; ++i) {
        pred[i] = static_cast<VertexDesc>(i);
    }

    visited[source] = true;
    q.push(source);

    while (!q.empty()) {
        VertexDesc current = q.front();
        q.pop();

        for (auto [e, eend] = boost::out_edges(current, g); e != eend; ++e) {
            VertexDesc next = boost::target(*e, g);
            if (!visited[next]) {
                visited[next] = true;
                pred[next] = current;
                if (next == target) {
                    q = {};
                    break;
                }
                q.push(next);
            }
        }
    }

    if (!visited[target]) {
        throw std::runtime_error("Node not reachable");
    }

    std::vector<NodeID> path;
    for (VertexDesc curr = target; curr != source; curr = pred[curr]) {
        path.push_back(bgl_to_id[curr]);
    }
    path.push_back(bgl_to_id[source]);
    std::reverse(path.begin(), path.end());
    return path;
}

template <typename GraphWrapper>
requires(GraphWrapper::has_builtin_edge_weight)
auto dijkstra_path(const GraphWrapper& G, const typename GraphWrapper::NodeType& source_id, const typename GraphWrapper::NodeType& target_id) {
    using NodeID = typename GraphWrapper::NodeType;
    using VertexDesc = typename GraphWrapper::VertexDesc;
    using Distance = typename GraphWrapper::EdgeWeightType;
    auto& g = G.get_impl();
    auto& id_to_bgl = G.get_id_to_bgl_map();
    auto& bgl_to_id = G.get_bgl_to_id_map();

    if (id_to_bgl.find(source_id) == id_to_bgl.end() || id_to_bgl.find(target_id) == id_to_bgl.end()) {
        throw std::runtime_error("Source or target node not found in graph.");
    }
    VertexDesc source = id_to_bgl.at(source_id);
    VertexDesc target = id_to_bgl.at(target_id);

    size_t n = boost::num_vertices(g);
    std::vector<Distance> dist(n);
    std::vector<VertexDesc> pred(n);

    boost::dijkstra_shortest_paths(g, source, 
        boost::distance_map(boost::make_iterator_property_map(dist.begin(), boost::get(boost::vertex_index, g)))
        .predecessor_map(boost::make_iterator_property_map(pred.begin(), boost::get(boost::vertex_index, g))));

    if (pred[target] == target && source != target) {
        throw std::runtime_error("Node not reachable");
    }

    std::vector<NodeID> path;
    for (VertexDesc curr = target; curr != source; curr = pred[curr]) {
        path.push_back(bgl_to_id[curr]);
    }
    path.push_back(bgl_to_id[source]);
    std::reverse(path.begin(), path.end());
    return path;
}

template <typename GraphWrapper>
requires(GraphWrapper::has_builtin_edge_weight)
auto single_source_dijkstra(const GraphWrapper& G, const typename GraphWrapper::NodeType& source_id) {
    using NodeID = typename GraphWrapper::NodeType;
    using VertexDesc = typename GraphWrapper::VertexDesc;
    using Distance = typename GraphWrapper::EdgeWeightType;

    const auto& g = G.get_impl();
    const auto& id_to_bgl = G.get_id_to_bgl_map();
    const auto& bgl_to_id = G.get_bgl_to_id_map();

    if (id_to_bgl.find(source_id) == id_to_bgl.end()) {
        throw std::runtime_error("Source node not found in graph.");
    }

    const VertexDesc source = id_to_bgl.at(source_id);
    const size_t n = boost::num_vertices(g);
    std::vector<Distance> dist(n, std::numeric_limits<Distance>::max());
    std::vector<VertexDesc> pred(n);
    for (size_t i = 0; i < n; ++i) {
        pred[i] = static_cast<VertexDesc>(i);
    }

    boost::dijkstra_shortest_paths(
        g,
        source,
        boost::distance_map(boost::make_iterator_property_map(dist.begin(), boost::get(boost::vertex_index, g)))
            .predecessor_map(boost::make_iterator_property_map(pred.begin(), boost::get(boost::vertex_index, g)))
    );

    SingleSourceShortestPathResult<NodeID, Distance> result;
    for (size_t i = 0; i < n; ++i) {
        result.distance[bgl_to_id[i]] = dist[i];
        result.predecessor[bgl_to_id[i]] = bgl_to_id[pred[i]];
    }
    result.paths = build_single_source_paths<NodeID, Distance>(bgl_to_id, dist, pred);
    return result;
}

template <typename GraphWrapper>
auto shortest_path(const GraphWrapper& G, const typename GraphWrapper::NodeType& source_id, const typename GraphWrapper::NodeType& target_id, const std::string& weight) {
    if (weight.empty()) {
        return shortest_path(G, source_id, target_id);
    }
    if (weight == "weight") {
        return dijkstra_path(G, source_id, target_id);
    }
    throw std::runtime_error("Unsupported weight attribute: nxpp currently supports only the built-in edge weight property named 'weight'.");
}

template <typename GraphWrapper>
requires(GraphWrapper::has_builtin_edge_weight)
auto dijkstra_path(const GraphWrapper& G, const typename GraphWrapper::NodeType& source_id, const typename GraphWrapper::NodeType& target_id, const std::string& weight) {
    if (weight.empty() || weight == "weight") {
        return dijkstra_path(G, source_id, target_id);
    }
    throw std::runtime_error("Unsupported weight attribute: nxpp currently supports only the built-in edge weight property named 'weight'.");
}

template <typename GraphWrapper>
double shortest_path_length(const GraphWrapper& G, const typename GraphWrapper::NodeType& source_id, const typename GraphWrapper::NodeType& target_id) {
    const auto path = shortest_path(G, source_id, target_id);
    if (path.empty()) {
        throw std::runtime_error("Node not reachable");
    }
    return static_cast<double>(path.size() - 1);
}

template <typename GraphWrapper>
double shortest_path_length(const GraphWrapper& G, const typename GraphWrapper::NodeType& source_id, const typename GraphWrapper::NodeType& target_id, const std::string& weight) {
    if (weight.empty()) {
        return shortest_path_length(G, source_id, target_id);
    }
    if (weight == "weight") {
        return dijkstra_path_length(G, source_id, target_id);
    }
    throw std::runtime_error("Unsupported weight attribute: nxpp currently supports only the built-in edge weight property named 'weight'.");
}

template <typename GraphWrapper>
requires(GraphWrapper::has_builtin_edge_weight)
auto dijkstra_path_length(const GraphWrapper& G, const typename GraphWrapper::NodeType& source_id) {
    return single_source_dijkstra(G, source_id).distance;
}

template <typename GraphWrapper>
requires(GraphWrapper::has_builtin_edge_weight)
auto dijkstra_path_length(const GraphWrapper& G, const typename GraphWrapper::NodeType& source_id, const typename GraphWrapper::NodeType& target_id) {
    const auto distances = dijkstra_path_length(G, source_id);
    auto it = distances.find(target_id);
    if (it == distances.end()) {
        throw std::runtime_error("Target node not found in graph.");
    }
    return it->second;
}

template <typename GraphWrapper>
requires(GraphWrapper::has_builtin_edge_weight)
auto dijkstra_path_length(const GraphWrapper& G, const typename GraphWrapper::NodeType& source_id, const typename GraphWrapper::NodeType& target_id, const std::string& weight) {
    if (weight.empty() || weight == "weight") {
        return dijkstra_path_length(G, source_id, target_id);
    }
    throw std::runtime_error("Unsupported weight attribute: nxpp currently supports only the built-in edge weight property named 'weight'.");
}

template <typename GraphWrapper>
requires(GraphWrapper::has_builtin_edge_weight)
auto bellman_ford_path(const GraphWrapper& G, const typename GraphWrapper::NodeType& source_id, const typename GraphWrapper::NodeType& target_id) {
    using NodeID = typename GraphWrapper::NodeType;
    using VertexDesc = typename GraphWrapper::VertexDesc;
    using Distance = typename GraphWrapper::EdgeWeightType;

    const auto& g = G.get_impl();
    const auto& id_to_bgl = G.get_id_to_bgl_map();
    const auto& bgl_to_id = G.get_bgl_to_id_map();

    if (id_to_bgl.find(source_id) == id_to_bgl.end() || id_to_bgl.find(target_id) == id_to_bgl.end()) {
        throw std::runtime_error("Source or target node not found in graph.");
    }

    VertexDesc source = id_to_bgl.at(source_id);
    VertexDesc target = id_to_bgl.at(target_id);

    const size_t n = boost::num_vertices(g);
    std::vector<Distance> dist(n, std::numeric_limits<Distance>::max());
    std::vector<VertexDesc> pred(n);

    for (size_t i = 0; i < n; ++i) {
        pred[i] = static_cast<VertexDesc>(i);
    }
    dist[source] = Distance{};

    const bool ok = boost::bellman_ford_shortest_paths(
        g,
        static_cast<int>(n),
        boost::weight_map(boost::get(boost::edge_weight, g))
            .distance_map(boost::make_iterator_property_map(dist.begin(), boost::get(boost::vertex_index, g)))
            .predecessor_map(boost::make_iterator_property_map(pred.begin(), boost::get(boost::vertex_index, g)))
            .root_vertex(source)
    );

    if (!ok) {
        throw std::runtime_error("Bellman-Ford failed: negative cycle detected.");
    }

    if (dist[target] == std::numeric_limits<Distance>::max()) {
        throw std::runtime_error("Node not reachable");
    }

    std::vector<NodeID> path;
    for (VertexDesc curr = target; curr != source; curr = pred[curr]) {
        path.push_back(bgl_to_id[curr]);
    }
    path.push_back(bgl_to_id[source]);
    std::reverse(path.begin(), path.end());
    return path;
}

template <typename GraphWrapper>
requires(GraphWrapper::has_builtin_edge_weight)
auto bellman_ford_shortest_paths(const GraphWrapper& G, const typename GraphWrapper::NodeType& source_id) {
    using NodeID = typename GraphWrapper::NodeType;
    using VertexDesc = typename GraphWrapper::VertexDesc;
    using Distance = typename GraphWrapper::EdgeWeightType;

    const auto& g = G.get_impl();
    const auto& id_to_bgl = G.get_id_to_bgl_map();
    const auto& bgl_to_id = G.get_bgl_to_id_map();

    if (id_to_bgl.find(source_id) == id_to_bgl.end()) {
        throw std::runtime_error("Source node not found in graph.");
    }

    const VertexDesc source = id_to_bgl.at(source_id);
    const size_t n = boost::num_vertices(g);
    std::vector<Distance> dist(n, std::numeric_limits<Distance>::max());
    std::vector<VertexDesc> pred(n);
    for (size_t i = 0; i < n; ++i) {
        pred[i] = static_cast<VertexDesc>(i);
    }
    dist[source] = Distance{};

    const bool ok = boost::bellman_ford_shortest_paths(
        g,
        static_cast<int>(n),
        boost::weight_map(boost::get(boost::edge_weight, g))
            .distance_map(boost::make_iterator_property_map(dist.begin(), boost::get(boost::vertex_index, g)))
            .predecessor_map(boost::make_iterator_property_map(pred.begin(), boost::get(boost::vertex_index, g)))
            .root_vertex(source)
    );

    if (!ok) {
        throw std::runtime_error("Bellman-Ford failed: negative cycle detected.");
    }

    SingleSourceShortestPathResult<NodeID, Distance> result;
    for (size_t i = 0; i < n; ++i) {
        result.distance[bgl_to_id[i]] = dist[i];
        result.predecessor[bgl_to_id[i]] = bgl_to_id[pred[i]];
    }
    result.paths = build_single_source_paths<NodeID, Distance>(bgl_to_id, dist, pred);
    return result;
}

template <typename GraphWrapper>
requires(GraphWrapper::has_builtin_edge_weight)
auto single_source_bellman_ford(const GraphWrapper& G, const typename GraphWrapper::NodeType& source_id) {
    return bellman_ford_shortest_paths(G, source_id);
}

template <typename GraphWrapper>
requires(GraphWrapper::has_builtin_edge_weight)
auto bellman_ford_path(const GraphWrapper& G, const typename GraphWrapper::NodeType& source_id, const typename GraphWrapper::NodeType& target_id, const std::string& weight) {
    if (weight.empty() || weight == "weight") {
        return bellman_ford_path(G, source_id, target_id);
    }
    throw std::runtime_error("Unsupported weight attribute: nxpp currently supports only the built-in edge weight property named 'weight'.");
}

template <typename GraphWrapper>
requires(GraphWrapper::has_builtin_edge_weight)
auto bellman_ford_path_length(const GraphWrapper& G, const typename GraphWrapper::NodeType& source_id, const typename GraphWrapper::NodeType& target_id) {
    using Distance = typename GraphWrapper::EdgeWeightType;
    const auto path = bellman_ford_path(G, source_id, target_id);
    if (path.empty()) {
        throw std::runtime_error("Node not reachable");
    }

    Distance total{};
    for (size_t i = 0; i + 1 < path.size(); ++i) {
        total += G.get_edge_weight(path[i], path[i + 1]);
    }
    return total;
}

template <typename GraphWrapper>
requires(GraphWrapper::has_builtin_edge_weight)
auto bellman_ford_path_length(const GraphWrapper& G, const typename GraphWrapper::NodeType& source_id, const typename GraphWrapper::NodeType& target_id, const std::string& weight) {
    if (weight.empty() || weight == "weight") {
        return bellman_ford_path_length(G, source_id, target_id);
    }
    throw std::runtime_error("Unsupported weight attribute: nxpp currently supports only the built-in edge weight property named 'weight'.");
}

template <typename GraphWrapper>
requires(GraphWrapper::has_builtin_edge_weight)
auto dag_shortest_paths(const GraphWrapper& G, const typename GraphWrapper::NodeType& source_id) {
    using NodeID = typename GraphWrapper::NodeType;
    using VertexDesc = typename GraphWrapper::VertexDesc;
    using Distance = typename GraphWrapper::EdgeWeightType;

    const auto& g = G.get_impl();
    const auto& id_to_bgl = G.get_id_to_bgl_map();
    const auto& bgl_to_id = G.get_bgl_to_id_map();

    if (id_to_bgl.find(source_id) == id_to_bgl.end()) {
        throw std::runtime_error("Source node not found in graph.");
    }

    VertexDesc source = id_to_bgl.at(source_id);
    const size_t n = boost::num_vertices(g);
    std::vector<Distance> dist(n, std::numeric_limits<Distance>::max());

    boost::dag_shortest_paths(
        g,
        source,
        boost::distance_map(boost::make_iterator_property_map(dist.begin(), boost::get(boost::vertex_index, g)))
    );

    std::unordered_map<NodeID, Distance> result;
    for (size_t i = 0; i < n; ++i) {
        result[bgl_to_id[i]] = dist[i];
    }
    return result;
}

template <typename GraphWrapper>
requires(GraphWrapper::has_builtin_edge_weight)
auto single_source_dag_shortest_paths(const GraphWrapper& G, const typename GraphWrapper::NodeType& source_id) {
    using NodeID = typename GraphWrapper::NodeType;
    using VertexDesc = typename GraphWrapper::VertexDesc;
    using Distance = typename GraphWrapper::EdgeWeightType;

    const auto& g = G.get_impl();
    const auto& id_to_bgl = G.get_id_to_bgl_map();
    const auto& bgl_to_id = G.get_bgl_to_id_map();

    if (id_to_bgl.find(source_id) == id_to_bgl.end()) {
        throw std::runtime_error("Source node not found in graph.");
    }

    const VertexDesc source = id_to_bgl.at(source_id);
    const size_t n = boost::num_vertices(g);
    std::vector<Distance> dist(n, std::numeric_limits<Distance>::max());
    std::vector<VertexDesc> pred(n);
    for (size_t i = 0; i < n; ++i) {
        pred[i] = static_cast<VertexDesc>(i);
    }

    boost::dag_shortest_paths(
        g,
        source,
        boost::distance_map(boost::make_iterator_property_map(dist.begin(), boost::get(boost::vertex_index, g)))
            .predecessor_map(boost::make_iterator_property_map(pred.begin(), boost::get(boost::vertex_index, g)))
    );

    SingleSourceShortestPathResult<NodeID, Distance> result;
    for (size_t i = 0; i < n; ++i) {
        result.distance[bgl_to_id[i]] = dist[i];
        result.predecessor[bgl_to_id[i]] = bgl_to_id[pred[i]];
    }
    result.paths = build_single_source_paths<NodeID, Distance>(bgl_to_id, dist, pred);
    return result;
}

template <typename GraphWrapper>
requires(GraphWrapper::has_builtin_edge_weight)
auto floyd_warshall_all_pairs_shortest_paths(const GraphWrapper& G) {
    using NodeID = typename GraphWrapper::NodeType;
    using Distance = typename GraphWrapper::EdgeWeightType;

    const auto& g = G.get_impl();
    const auto& bgl_to_id = G.get_bgl_to_id_map();
    const size_t n = boost::num_vertices(g);

    std::vector<std::vector<Distance>> internal_matrix(n, std::vector<Distance>(n));
    boost::floyd_warshall_all_pairs_shortest_paths(g, internal_matrix);

    std::vector<std::size_t> order(n);
    for (std::size_t i = 0; i < n; ++i) {
        order[i] = i;
    }

    if constexpr (std::is_arithmetic_v<NodeID> || std::is_same_v<NodeID, std::string>) {
        std::sort(order.begin(), order.end(), [&](std::size_t lhs, std::size_t rhs) {
            return bgl_to_id[lhs] < bgl_to_id[rhs];
        });
    }

    std::vector<std::vector<Distance>> matrix(n, std::vector<Distance>(n));
    for (std::size_t i = 0; i < n; ++i) {
        for (std::size_t j = 0; j < n; ++j) {
            matrix[i][j] = internal_matrix[order[i]][order[j]];
        }
    }

    return matrix;
}

template <typename GraphWrapper>
requires(GraphWrapper::has_builtin_edge_weight)
auto floyd_warshall_all_pairs_shortest_paths_map(const GraphWrapper& G) {
    using NodeID = typename GraphWrapper::NodeType;
    using Distance = typename GraphWrapper::EdgeWeightType;

    const auto& bgl_to_id = G.get_bgl_to_id_map();
    const auto& g = G.get_impl();
    const size_t n = boost::num_vertices(g);

    std::vector<std::size_t> order(n);
    for (std::size_t i = 0; i < n; ++i) {
        order[i] = i;
    }

    if constexpr (std::is_arithmetic_v<NodeID> || std::is_same_v<NodeID, std::string>) {
        std::sort(order.begin(), order.end(), [&](std::size_t lhs, std::size_t rhs) {
            return bgl_to_id[lhs] < bgl_to_id[rhs];
        });
    }

    const auto matrix = floyd_warshall_all_pairs_shortest_paths(G);

    std::unordered_map<NodeID, std::unordered_map<NodeID, Distance>> result;
    for (size_t i = 0; i < n; ++i) {
        for (size_t j = 0; j < n; ++j) {
            result[bgl_to_id[order[i]]][bgl_to_id[order[j]]] = matrix[i][j];
        }
    }
    return result;
}

} // namespace nxpp

#endif // NXPP_MODULAR_SHORTEST_PATHS_HPP
