#ifndef NXPP_MODULAR_TRAVERSALS_HPP
#define NXPP_MODULAR_TRAVERSALS_HPP

// Generated from include/nxpp.hpp by scripts/sync_modular_headers.py.
// Do not edit this file directly: keep include/nxpp.hpp as the single source of truth.

#include "types.hpp"

namespace nxpp {

template <typename NodeID, typename Edge>
class GenericBfsEdgeVisitor : public boost::default_bfs_visitor {
public:
    GenericBfsEdgeVisitor(std::vector<std::pair<NodeID, NodeID>>& edges, const std::vector<NodeID>& bgl_to_id)
        : tree_edges(edges), bgl_to_id(bgl_to_id) {}

    template <typename G>
    void tree_edge(Edge e, const G& g) {
        NodeID u = bgl_to_id[boost::source(e, g)];
        NodeID v = bgl_to_id[boost::target(e, g)];
        tree_edges.emplace_back(u, v);
    }
private:
    std::vector<std::pair<NodeID, NodeID>>& tree_edges;
    const std::vector<NodeID>& bgl_to_id;
};

template <typename GraphWrapper>
auto bfs_edges(const GraphWrapper& G, const typename GraphWrapper::NodeType& start) {
    using NodeID = typename GraphWrapper::NodeType;
    std::vector<std::pair<NodeID, NodeID>> edges;
    using GraphType = typename GraphWrapper::GraphType;
    using EdgeType = typename boost::graph_traits<GraphType>::edge_descriptor;
    
    if (!G.has_node(start)) throw std::runtime_error("Start node not found in graph");
    auto start_bgl = G.get_id_to_bgl_map().at(start);

    GenericBfsEdgeVisitor<NodeID, EdgeType> vis(edges, G.get_bgl_to_id_map());
    boost::breadth_first_search(G.get_impl(), start_bgl, boost::visitor(vis));
    return edges;
}

template <typename GraphWrapper>
auto bfs_tree(const GraphWrapper& G, const typename GraphWrapper::NodeType& start) {
    using NodeID = typename GraphWrapper::NodeType;
    Graph<NodeID, double, GraphWrapper::is_directed> tree;

    if (!G.has_node(start)) {
        throw std::runtime_error("Start node not found in graph");
    }

    tree.add_node(start);
    for (const auto& [u, v] : bfs_edges(G, start)) {
        tree.add_edge(u, v);
    }
    return tree;
}

template <typename GraphWrapper>
auto bfs_successors(const GraphWrapper& G, const typename GraphWrapper::NodeType& start) {
    using NodeID = typename GraphWrapper::NodeType;

    if (!G.has_node(start)) {
        throw std::runtime_error("Start node not found in graph");
    }

    std::unordered_map<NodeID, std::vector<NodeID>> result;
    for (const auto& [u, v] : bfs_edges(G, start)) {
        result[u].push_back(v);
    }
    return result;
}

template <typename NodeID, typename Edge, typename OnVertex, typename OnTreeEdge>
class GenericBfsVisitVisitor : public boost::default_bfs_visitor {
public:
    GenericBfsVisitVisitor(const std::vector<NodeID>& bgl_to_id, OnVertex& on_vertex, OnTreeEdge& on_tree_edge)
        : bgl_to_id(bgl_to_id), on_vertex(on_vertex), on_tree_edge(on_tree_edge) {}

    template <typename G>
    void examine_vertex(typename boost::graph_traits<G>::vertex_descriptor u, const G&) const {
        on_vertex(bgl_to_id[u]);
    }

    template <typename G>
    void tree_edge(Edge e, const G& g) const {
        on_tree_edge(bgl_to_id[boost::source(e, g)], bgl_to_id[boost::target(e, g)]);
    }

private:
    const std::vector<NodeID>& bgl_to_id;
    OnVertex& on_vertex;
    OnTreeEdge& on_tree_edge;
};

template <typename Visitor, typename NodeID, typename GraphWrapper>
void bfs_dispatch_examine_vertex(Visitor& visitor, const NodeID& u, const GraphWrapper& G) {
    if constexpr (requires { visitor.examine_vertex(u, G); }) {
        visitor.examine_vertex(u, G);
    }
}

template <typename Visitor, typename NodeID, typename GraphWrapper>
void bfs_dispatch_tree_edge(Visitor& visitor, const NodeID& u, const NodeID& v, const GraphWrapper& G) {
    if constexpr (requires { visitor.tree_edge(u, v, G); }) {
        visitor.tree_edge(u, v, G);
    }
}

template <typename NodeID, typename Edge, typename GraphWrapper, typename Visitor>
class GenericBfsObjectVisitor : public boost::default_bfs_visitor {
public:
    GenericBfsObjectVisitor(const GraphWrapper& graph_wrapper, Visitor& visitor)
        : graph_wrapper(graph_wrapper), visitor(visitor) {}

    template <typename G>
    void examine_vertex(typename boost::graph_traits<G>::vertex_descriptor u, const G&) const {
        bfs_dispatch_examine_vertex(visitor, graph_wrapper.get_bgl_to_id_map()[u], graph_wrapper);
    }

    template <typename G>
    void tree_edge(Edge e, const G& g) const {
        const auto& bgl_to_id = graph_wrapper.get_bgl_to_id_map();
        bfs_dispatch_tree_edge(
            visitor,
            bgl_to_id[boost::source(e, g)],
            bgl_to_id[boost::target(e, g)],
            graph_wrapper
        );
    }

private:
    const GraphWrapper& graph_wrapper;
    Visitor& visitor;
};

template <typename GraphWrapper, typename Visitor>
void breadth_first_search(const GraphWrapper& G, const typename GraphWrapper::NodeType& start, Visitor& visitor) {
    using NodeID = typename GraphWrapper::NodeType;
    using GraphType = typename GraphWrapper::GraphType;
    using EdgeType = typename boost::graph_traits<GraphType>::edge_descriptor;

    if (!G.has_node(start)) throw std::runtime_error("Start node not found in graph");
    auto start_bgl = G.get_id_to_bgl_map().at(start);

    GenericBfsObjectVisitor<NodeID, EdgeType, GraphWrapper, Visitor> vis(G, visitor);
    boost::breadth_first_search(G.get_impl(), start_bgl, boost::visitor(vis));
}

template <typename GraphWrapper, typename OnVertex, typename OnTreeEdge>
void bfs_visit(const GraphWrapper& G, const typename GraphWrapper::NodeType& start, OnVertex&& on_vertex, OnTreeEdge&& on_tree_edge) {
    struct callback_visitor {
        OnVertex& on_vertex;
        OnTreeEdge& on_tree_edge;

        void examine_vertex(const typename GraphWrapper::NodeType& u, const GraphWrapper&) {
            on_vertex(u);
        }

        void tree_edge(const typename GraphWrapper::NodeType& u, const typename GraphWrapper::NodeType& v, const GraphWrapper&) {
            on_tree_edge(u, v);
        }
    };

    auto on_vertex_fn = std::forward<OnVertex>(on_vertex);
    auto on_tree_edge_fn = std::forward<OnTreeEdge>(on_tree_edge);
    callback_visitor visitor{on_vertex_fn, on_tree_edge_fn};
    breadth_first_search(G, start, visitor);
}

template <typename NodeID, typename Edge>
class GenericDfsEdgeVisitor : public boost::default_dfs_visitor {
public:
    GenericDfsEdgeVisitor(std::vector<std::pair<NodeID, NodeID>>& edges, const std::vector<NodeID>& bgl_to_id)
        : tree_edges(edges), bgl_to_id(bgl_to_id) {}

    template <typename G>
    void tree_edge(Edge e, const G& g) {
        NodeID u = bgl_to_id[boost::source(e, g)];
        NodeID v = bgl_to_id[boost::target(e, g)];
        tree_edges.emplace_back(u, v);
    }
private:
    std::vector<std::pair<NodeID, NodeID>>& tree_edges;
    const std::vector<NodeID>& bgl_to_id;
};

template <typename GraphWrapper>
auto dfs_edges(const GraphWrapper& G, const typename GraphWrapper::NodeType& start) {
    using NodeID = typename GraphWrapper::NodeType;
    std::vector<std::pair<NodeID, NodeID>> edges;
    using GraphType = typename GraphWrapper::GraphType;
    using EdgeType = typename boost::graph_traits<GraphType>::edge_descriptor;
    
    if (!G.has_node(start)) throw std::runtime_error("Start node not found in graph");
    auto start_bgl = G.get_id_to_bgl_map().at(start);

    GenericDfsEdgeVisitor<NodeID, EdgeType> vis(edges, G.get_bgl_to_id_map());
    boost::depth_first_search(G.get_impl(), boost::root_vertex(start_bgl).visitor(vis));
    return edges;
}

template <typename GraphWrapper>
auto dfs_tree(const GraphWrapper& G, const typename GraphWrapper::NodeType& start) {
    using NodeID = typename GraphWrapper::NodeType;
    Graph<NodeID, double, GraphWrapper::is_directed> tree;

    if (!G.has_node(start)) {
        throw std::runtime_error("Start node not found in graph");
    }

    tree.add_node(start);
    for (const auto& [u, v] : dfs_edges(G, start)) {
        tree.add_edge(u, v);
    }
    return tree;
}

template <typename GraphWrapper>
auto dfs_predecessors(const GraphWrapper& G, const typename GraphWrapper::NodeType& start) {
    using NodeID = typename GraphWrapper::NodeType;

    if (!G.has_node(start)) {
        throw std::runtime_error("Start node not found in graph");
    }

    std::unordered_map<NodeID, NodeID> result;
    for (const auto& [u, v] : dfs_edges(G, start)) {
        result[v] = u;
    }
    return result;
}

template <typename GraphWrapper>
auto dfs_successors(const GraphWrapper& G, const typename GraphWrapper::NodeType& start) {
    using NodeID = typename GraphWrapper::NodeType;

    if (!G.has_node(start)) {
        throw std::runtime_error("Start node not found in graph");
    }

    std::unordered_map<NodeID, std::vector<NodeID>> result;
    for (const auto& [u, v] : dfs_edges(G, start)) {
        result[u].push_back(v);
    }
    return result;
}

template <typename NodeID, typename VertexDesc>
std::unordered_map<NodeID, std::vector<NodeID>> build_single_source_paths(
    const std::vector<NodeID>& bgl_to_id,
    const std::vector<double>& dist,
    const std::vector<VertexDesc>& pred
) {
    std::unordered_map<NodeID, std::vector<NodeID>> paths;
    const auto unreachable = std::numeric_limits<double>::max();

    for (size_t i = 0; i < bgl_to_id.size(); ++i) {
        const NodeID target_id = bgl_to_id[i];
        if (dist[i] == unreachable) {
            continue;
        }

        std::vector<NodeID> path;
        VertexDesc current = static_cast<VertexDesc>(i);
        while (true) {
            path.push_back(bgl_to_id[current]);
            if (pred[current] == current) {
                break;
            }
            current = pred[current];
        }
        std::reverse(path.begin(), path.end());
        paths[target_id] = std::move(path);
    }

    return paths;
}

template <typename NodeID, typename Edge, typename OnTreeEdge, typename OnBackEdge>
class GenericDfsVisitVisitor : public boost::default_dfs_visitor {
public:
    GenericDfsVisitVisitor(const std::vector<NodeID>& bgl_to_id, OnTreeEdge& on_tree_edge, OnBackEdge& on_back_edge)
        : bgl_to_id(bgl_to_id), on_tree_edge(on_tree_edge), on_back_edge(on_back_edge) {}

    template <typename G>
    void tree_edge(Edge e, const G& g) const {
        on_tree_edge(bgl_to_id[boost::source(e, g)], bgl_to_id[boost::target(e, g)]);
    }

    template <typename G>
    void back_edge(Edge e, const G& g) const {
        on_back_edge(bgl_to_id[boost::source(e, g)], bgl_to_id[boost::target(e, g)]);
    }

private:
    const std::vector<NodeID>& bgl_to_id;
    OnTreeEdge& on_tree_edge;
    OnBackEdge& on_back_edge;
};

template <typename Visitor, typename NodeID, typename GraphWrapper>
void dfs_dispatch_tree_edge(Visitor& visitor, const NodeID& u, const NodeID& v, const GraphWrapper& G) {
    if constexpr (requires { visitor.tree_edge(u, v, G); }) {
        visitor.tree_edge(u, v, G);
    }
}

template <typename Visitor, typename NodeID, typename GraphWrapper>
void dfs_dispatch_back_edge(Visitor& visitor, const NodeID& u, const NodeID& v, const GraphWrapper& G) {
    if constexpr (requires { visitor.back_edge(u, v, G); }) {
        visitor.back_edge(u, v, G);
    }
}

template <typename NodeID, typename Edge, typename GraphWrapper, typename Visitor>
class GenericDfsObjectVisitor : public boost::default_dfs_visitor {
public:
    GenericDfsObjectVisitor(const GraphWrapper& graph_wrapper, Visitor& visitor)
        : graph_wrapper(graph_wrapper), visitor(visitor) {}

    template <typename G>
    void tree_edge(Edge e, const G& g) const {
        const auto& bgl_to_id = graph_wrapper.get_bgl_to_id_map();
        dfs_dispatch_tree_edge(
            visitor,
            bgl_to_id[boost::source(e, g)],
            bgl_to_id[boost::target(e, g)],
            graph_wrapper
        );
    }

    template <typename G>
    void back_edge(Edge e, const G& g) const {
        const auto& bgl_to_id = graph_wrapper.get_bgl_to_id_map();
        dfs_dispatch_back_edge(
            visitor,
            bgl_to_id[boost::source(e, g)],
            bgl_to_id[boost::target(e, g)],
            graph_wrapper
        );
    }

private:
    const GraphWrapper& graph_wrapper;
    Visitor& visitor;
};

template <typename GraphWrapper, typename Visitor>
void depth_first_search(const GraphWrapper& G, const typename GraphWrapper::NodeType& start, Visitor& visitor) {
    using NodeID = typename GraphWrapper::NodeType;
    using GraphType = typename GraphWrapper::GraphType;
    using EdgeType = typename boost::graph_traits<GraphType>::edge_descriptor;

    if (!G.has_node(start)) throw std::runtime_error("Start node not found in graph");
    auto start_bgl = G.get_id_to_bgl_map().at(start);

    GenericDfsObjectVisitor<NodeID, EdgeType, GraphWrapper, Visitor> vis(G, visitor);
    boost::depth_first_search(G.get_impl(), boost::root_vertex(start_bgl).visitor(vis));
}

template <typename GraphWrapper, typename OnTreeEdge, typename OnBackEdge>
void dfs_visit(const GraphWrapper& G, const typename GraphWrapper::NodeType& start, OnTreeEdge&& on_tree_edge, OnBackEdge&& on_back_edge) {
    struct callback_visitor {
        OnTreeEdge& on_tree_edge;
        OnBackEdge& on_back_edge;

        void tree_edge(const typename GraphWrapper::NodeType& u, const typename GraphWrapper::NodeType& v, const GraphWrapper&) {
            on_tree_edge(u, v);
        }

        void back_edge(const typename GraphWrapper::NodeType& u, const typename GraphWrapper::NodeType& v, const GraphWrapper&) {
            on_back_edge(u, v);
        }
    };

    auto on_tree_edge_fn = std::forward<OnTreeEdge>(on_tree_edge);
    auto on_back_edge_fn = std::forward<OnBackEdge>(on_back_edge);
    callback_visitor visitor{on_tree_edge_fn, on_back_edge_fn};
    depth_first_search(G, start, visitor);
}

} // namespace nxpp

#endif // NXPP_MODULAR_TRAVERSALS_HPP
