#ifndef NXPP_MODULAR_TYPES_HPP
#define NXPP_MODULAR_TYPES_HPP

// Generated from include/nxpp.hpp by scripts/sync_modular_headers.py.
// Do not edit this file directly: keep include/nxpp.hpp as the single source of truth.

#include "graph.hpp"

namespace nxpp {

using WeightedGraphInt = Graph<int>;
using WeightedDiGraphInt = Graph<int, double, true>;
using WeightedGraphStr = Graph<std::string>;
using WeightedMultiGraphInt = Graph<int, double, false, true>;
using WeightedMultiDiGraphInt = Graph<int, double, true, true>;

using WeightedDiGraph = Graph<std::string, double, true>;
using WeightedMultiGraph = Graph<std::string, double, false, true>;
using WeightedMultiDiGraph = Graph<std::string, double, true, true>;

using GraphInt = Graph<int>;
using DiGraphInt = Graph<int, double, true>;
using GraphStr = Graph<std::string>;
using MultiGraphInt = Graph<int, double, false, true>;
using MultiDiGraphInt = Graph<int, double, true, true>;

using DiGraph = Graph<std::string, double, true>;
using MultiGraph = Graph<std::string, double, false, true>;
using MultiDiGraph = Graph<std::string, double, true, true>;

using UnweightedGraphInt = Graph<int, double, false, false, false>;
using UnweightedDiGraphInt = Graph<int, double, true, false, false>;
using UnweightedGraphStr = Graph<std::string, double, false, false, false>;
using UnweightedDiGraph = Graph<std::string, double, true, false, false>;
using UnweightedMultiGraphInt = Graph<int, double, false, true, false>;
using UnweightedMultiDiGraphInt = Graph<int, double, true, true, false>;
using UnweightedMultiGraph = Graph<std::string, double, false, true, false>;
using UnweightedMultiDiGraph = Graph<std::string, double, true, true, false>;

template <typename NodeID>
struct MaximumFlowResult {
    long value = 0;
    std::map<std::pair<NodeID, NodeID>, long> flow;
};

template <typename NodeID>
struct MinCostMaxFlowResult {
    long flow = 0;
    long cost = 0;
    std::map<std::pair<NodeID, NodeID>, long> edge_flows;
};

namespace detail {

template <typename NodeID>
struct MinCostFlowState {
    using FlowTraits = boost::adjacency_list_traits<boost::vecS, boost::vecS, boost::directedS>;
    using FlowGraph = boost::adjacency_list<
        boost::vecS,
        boost::vecS,
        boost::directedS,
        boost::no_property,
        boost::property<
            boost::edge_weight_t,
            long,
            boost::property<
                boost::edge_capacity_t,
                long,
                boost::property<
                    boost::edge_residual_capacity_t,
                    long,
                    boost::property<boost::edge_reverse_t, typename FlowTraits::edge_descriptor>
                >
            >
        >
    >;
    using WeightMap = typename boost::property_map<FlowGraph, boost::edge_weight_t>::type;
    using CapacityMap = typename boost::property_map<FlowGraph, boost::edge_capacity_t>::type;
    using ResidualMap = typename boost::property_map<FlowGraph, boost::edge_residual_capacity_t>::type;
    using ReverseMap = typename boost::property_map<FlowGraph, boost::edge_reverse_t>::type;
    using FlowEdgeDesc = typename boost::graph_traits<FlowGraph>::edge_descriptor;

    FlowGraph flow_graph;
    WeightMap weight;
    CapacityMap capacity;
    ResidualMap residual;
    ReverseMap reverse;
    std::unordered_map<NodeID, std::size_t> node_to_index;
    std::map<std::pair<NodeID, NodeID>, FlowEdgeDesc> original_edges;
    NodeID source_id;
    NodeID target_id;
    long value = 0;
    long cost = 0;

    MinCostFlowState()
        : flow_graph(),
          weight(boost::get(boost::edge_weight, flow_graph)),
          capacity(boost::get(boost::edge_capacity, flow_graph)),
          residual(boost::get(boost::edge_residual_capacity, flow_graph)),
          reverse(boost::get(boost::edge_reverse, flow_graph)) {}
};

template <typename GraphWrapper>
auto& min_cost_flow_cache() {
    using NodeID = typename GraphWrapper::NodeType;
    static std::unordered_map<const void*, std::unique_ptr<MinCostFlowState<NodeID>>> cache;
    return cache;
}

} // namespace detail

template <typename NodeID>
struct MinimumCutResult {
    long value = 0;
    std::vector<NodeID> reachable;
    std::vector<NodeID> non_reachable;
    std::vector<std::pair<NodeID, NodeID>> cut_edges;
};

template <typename NodeID>
struct SingleSourceShortestPathResult {
    std::unordered_map<NodeID, double> distance;
    std::unordered_map<NodeID, NodeID> predecessor;
    std::unordered_map<NodeID, std::vector<NodeID>> paths;
};

template <typename Key, typename Value>
class lookup_map {
public:
    using storage_type = std::unordered_map<Key, Value>;
    using iterator = typename storage_type::iterator;
    using const_iterator = typename storage_type::const_iterator;

    Value& operator[](const Key& key) {
        return data[key];
    }

    const Value& operator[](const Key& key) const {
        return data.at(key);
    }

    Value& at(const Key& key) {
        return data.at(key);
    }

    const Value& at(const Key& key) const {
        return data.at(key);
    }

    iterator begin() { return data.begin(); }
    iterator end() { return data.end(); }
    const_iterator begin() const { return data.begin(); }
    const_iterator end() const { return data.end(); }
    const_iterator cbegin() const { return data.cbegin(); }
    const_iterator cend() const { return data.cend(); }

private:
    storage_type data;
};

template <typename GraphWrapper>
class default_graph_visitor {
public:
    using NodeID = typename GraphWrapper::NodeType;

    void examine_vertex(const NodeID&, const GraphWrapper&) {}
    void tree_edge(const NodeID&, const NodeID&, const GraphWrapper&) {}
    void back_edge(const NodeID&, const NodeID&, const GraphWrapper&) {}
};

} // namespace nxpp

#endif // NXPP_MODULAR_TYPES_HPP
