#!/usr/bin/env python3

from __future__ import annotations

import argparse
import re
from pathlib import Path


INCLUDE_PATTERN = re.compile(r'^\s*#include\s+"([^"]+)"\s*$')


def parse_args() -> argparse.Namespace:
    root = Path(__file__).resolve().parents[1]
    return argparse.ArgumentParser(description="Build a standalone nxpp single header").parse_args()


def resolve_local_include(current_file: Path, include_target: str, include_root: Path) -> Path | None:
    candidates = [
        (current_file.parent / include_target).resolve(),
        (include_root / include_target).resolve(),
    ]
    for candidate in candidates:
        try:
            candidate.relative_to(include_root)
        except ValueError:
            continue
        if candidate.is_file():
            return candidate
    return None


def expand_file(path: Path, include_root: Path, seen: set[Path], output_lines: list[str]) -> None:
    resolved = path.resolve()
    if resolved in seen:
        return
    seen.add(resolved)

    output_lines.append(f"// Begin file: {resolved.relative_to(include_root.parent)}")
    for raw_line in resolved.read_text(encoding="utf-8").splitlines():
        stripped = raw_line.strip()
        if stripped == "#pragma once":
            continue

        match = INCLUDE_PATTERN.match(raw_line)
        if match:
            local_include = resolve_local_include(resolved, match.group(1), include_root)
            if local_include is not None:
                expand_file(local_include, include_root, seen, output_lines)
                continue

        output_lines.append(raw_line)
    output_lines.append(f"// End file: {resolved.relative_to(include_root.parent)}")
    output_lines.append("")


def main() -> int:
    parse_args()
    root = Path(__file__).resolve().parents[1]
    include_root = (root / "include").resolve()
    source_header = include_root / "nxpp.hpp"
    target_dir = root / "dist"
    target_header = target_dir / "nxpp.hpp"

    target_dir.mkdir(parents=True, exist_ok=True)

    expanded_lines = [
        "// Generated by scripts/build_single_header.py.",
        "// Do not edit this file directly; edit the modular headers under include/.",
        "",
        "#ifndef NXPP_SINGLE_HEADER_HPP",
        "#define NXPP_SINGLE_HEADER_HPP",
        "",
    ]

    seen: set[Path] = set()
    expand_file(source_header, include_root, seen, expanded_lines)
    expanded_lines.extend(
        [
            "#endif // NXPP_SINGLE_HEADER_HPP",
            "",
        ]
    )

    target_header.write_text("\n".join(expanded_lines), encoding="utf-8")
    print(f"Wrote {target_header}")
    print("Built a standalone single header by expanding local nxpp includes.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
