#!/usr/bin/env python3

from __future__ import annotations

from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
SOURCE_HEADER = ROOT / "include" / "nxpp.hpp"
TARGET_DIR = ROOT / "include_modular"

NOTICE = """// Generated from include/nxpp.hpp by scripts/sync_modular_headers.py.
// Do not edit this file directly: keep include/nxpp.hpp as the single source of truth.
"""


def extract_between(text: str, start_marker: str, end_marker: str) -> str:
    start = text.index(start_marker) + len(start_marker)
    end = text.index(end_marker, start)
    return text[start:end].strip("\n")


def build_base_preamble(text: str) -> str:
    prefix = text.split("namespace nxpp {\n", 1)[0]
    lines = prefix.splitlines()
    first_include_line = next(i for i, line in enumerate(lines) if line.startswith("#if !__has_include"))
    return "\n".join(lines[first_include_line:]).strip()


def render_header(*, guard: str, includes: list[str], body: str) -> str:
    include_block = "\n".join(includes)
    body = body.strip("\n")
    return (
        f"#ifndef {guard}\n"
        f"#define {guard}\n\n"
        f"{NOTICE}\n"
        f"{include_block}\n\n"
        f"namespace nxpp {{\n\n"
        f"{body}\n\n"
        f"}} // namespace nxpp\n\n"
        f"#endif // {guard}\n"
    )


def render_umbrella() -> str:
    guard = "NXPP_MODULAR_HPP"
    headers = [
        "base.hpp",
        "graph.hpp",
        "generators.hpp",
        "types.hpp",
        "traversals.hpp",
        "shortest_paths.hpp",
        "components.hpp",
    ]
    include_block = "\n".join(f'#include "{header}"' for header in headers)
    return (
        f"#ifndef {guard}\n"
        f"#define {guard}\n\n"
        f"{NOTICE}\n"
        f"{include_block}\n\n"
        f"#endif // {guard}\n"
    )


def main() -> None:
    text = SOURCE_HEADER.read_text(encoding="utf-8")

    base_preamble = build_base_preamble(text)
    base_body = extract_between(text, "namespace nxpp {\n", "\n// Core Graph Class")
    graph_body = extract_between(text, "// Core Graph Class\n", "\n// Generators")
    generators_body = extract_between(text, "// Generators\n", "\n// NetworkX-style Aliases")
    types_body = extract_between(text, "// NetworkX-style Aliases\n", "\n// Algorithms: Traversals")
    traversals_body = extract_between(text, "// Algorithms: Traversals\n", "\n// Algorithms: Shortest Paths")
    shortest_paths_body = extract_between(text, "// Algorithms: Shortest Paths\n", "\n// Algorithms: Components")
    components_body = extract_between(text, "// Algorithms: Components\n", "\n} // namespace nxpp")

    TARGET_DIR.mkdir(parents=True, exist_ok=True)

    files = {
        "base.hpp": render_header(
            guard="NXPP_MODULAR_BASE_HPP",
            includes=[base_preamble],
            body=base_body,
        ),
        "graph.hpp": render_header(
            guard="NXPP_MODULAR_GRAPH_HPP",
            includes=['#include "base.hpp"'],
            body=graph_body,
        ),
        "generators.hpp": render_header(
            guard="NXPP_MODULAR_GENERATORS_HPP",
            includes=['#include "graph.hpp"'],
            body=generators_body,
        ),
        "types.hpp": render_header(
            guard="NXPP_MODULAR_TYPES_HPP",
            includes=['#include "graph.hpp"'],
            body=types_body,
        ),
        "traversals.hpp": render_header(
            guard="NXPP_MODULAR_TRAVERSALS_HPP",
            includes=['#include "types.hpp"'],
            body=traversals_body,
        ),
        "shortest_paths.hpp": render_header(
            guard="NXPP_MODULAR_SHORTEST_PATHS_HPP",
            includes=['#include "traversals.hpp"'],
            body=shortest_paths_body,
        ),
        "components.hpp": render_header(
            guard="NXPP_MODULAR_COMPONENTS_HPP",
            includes=['#include "types.hpp"'],
            body=components_body,
        ),
        "nxpp.hpp": render_umbrella(),
    }

    for name, content in files.items():
        (TARGET_DIR / name).write_text(content, encoding="utf-8")


if __name__ == "__main__":
    main()
